/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'PropertyEscrow', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyEscrow__factory>
getContractFactory(name: 'PropertyLease', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyLease__factory>
getContractFactory(name: 'PropertyToken', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyToken__factory>
getContractFactory(name: 'PropertyOwnership', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.PropertyOwnership__factory>
getContractFactory(name: 'VerificationRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.VerificationRegistry__factory>

  getContractAt(name: 'PropertyEscrow', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyEscrow>
getContractAt(name: 'PropertyLease', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyLease>
getContractAt(name: 'PropertyToken', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyToken>
getContractAt(name: 'PropertyOwnership', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.PropertyOwnership>
getContractAt(name: 'VerificationRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.VerificationRegistry>

  deployContract(name: 'PropertyEscrow', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyEscrow>
deployContract(name: 'PropertyLease', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyLease>
deployContract(name: 'PropertyToken', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyToken>
deployContract(name: 'PropertyOwnership', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyOwnership>
deployContract(name: 'VerificationRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VerificationRegistry>

  deployContract(name: 'PropertyEscrow', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyEscrow>
deployContract(name: 'PropertyLease', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyLease>
deployContract(name: 'PropertyToken', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyToken>
deployContract(name: 'PropertyOwnership', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.PropertyOwnership>
deployContract(name: 'VerificationRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.VerificationRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  