/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PropertyOwnershipInterface extends Interface {
    getFunction(nameOrSignature: "addCoOwner" | "getOwnerProperties" | "getOwnershipPercentage" | "getPropertyDetails" | "getPropertyOwners" | "ownerProperties" | "properties" | "registerProperty" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipAdded" | "OwnershipRemoved" | "OwnershipTransferred" | "PropertyRegistered"): EventFragment;

    encodeFunctionData(functionFragment: 'addCoOwner', values: [string, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOwnerProperties', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getOwnershipPercentage', values: [string, AddressLike]): string;
encodeFunctionData(functionFragment: 'getPropertyDetails', values: [string]): string;
encodeFunctionData(functionFragment: 'getPropertyOwners', values: [string]): string;
encodeFunctionData(functionFragment: 'ownerProperties', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'properties', values: [string]): string;
encodeFunctionData(functionFragment: 'registerProperty', values: [string, BigNumberish, AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [string, AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addCoOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwnerProperties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOwnershipPercentage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPropertyDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPropertyOwners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ownerProperties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'properties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerProperty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace OwnershipAddedEvent {
      export type InputTuple = [propertyId: string, owner: AddressLike, percentage: BigNumberish];
      export type OutputTuple = [propertyId: string, owner: string, percentage: bigint];
      export interface OutputObject {propertyId: string, owner: string, percentage: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipRemovedEvent {
      export type InputTuple = [propertyId: string, owner: AddressLike];
      export type OutputTuple = [propertyId: string, owner: string];
      export interface OutputObject {propertyId: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [propertyId: string, from: AddressLike, to: AddressLike, percentage: BigNumberish];
      export type OutputTuple = [propertyId: string, from: string, to: string, percentage: bigint];
      export interface OutputObject {propertyId: string, from: string, to: string, percentage: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PropertyRegisteredEvent {
      export type InputTuple = [propertyId: string, totalValue: BigNumberish];
      export type OutputTuple = [propertyId: string, totalValue: bigint];
      export interface OutputObject {propertyId: string, totalValue: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PropertyOwnership extends BaseContract {
    
    connect(runner?: ContractRunner | null): PropertyOwnership;
    waitForDeployment(): Promise<this>;

    interface: PropertyOwnershipInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addCoOwner: TypedContractMethod<
      [_propertyId: string, _newOwner: AddressLike, _percentage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getOwnerProperties: TypedContractMethod<
      [_owner: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getOwnershipPercentage: TypedContractMethod<
      [_propertyId: string, _owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getPropertyDetails: TypedContractMethod<
      [_propertyId: string, ],
      [[string, bigint, bigint, bigint] & {propertyId: string, totalValue: bigint, createdAt: bigint, ownerCount: bigint }],
      'view'
    >
    

    
    getPropertyOwners: TypedContractMethod<
      [_propertyId: string, ],
      [[string[], bigint[]] & {owners: string[], percentages: bigint[] }],
      'view'
    >
    

    
    ownerProperties: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    properties: TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, bigint] & {propertyId: string, totalValue: bigint, createdAt: bigint }],
      'view'
    >
    

    
    registerProperty: TypedContractMethod<
      [_propertyId: string, _totalValue: BigNumberish, _initialOwners: AddressLike[], _percentages: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [_propertyId: string, _from: AddressLike, _to: AddressLike, _percentage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addCoOwner'): TypedContractMethod<
      [_propertyId: string, _newOwner: AddressLike, _percentage: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getOwnerProperties'): TypedContractMethod<
      [_owner: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOwnershipPercentage'): TypedContractMethod<
      [_propertyId: string, _owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPropertyDetails'): TypedContractMethod<
      [_propertyId: string, ],
      [[string, bigint, bigint, bigint] & {propertyId: string, totalValue: bigint, createdAt: bigint, ownerCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPropertyOwners'): TypedContractMethod<
      [_propertyId: string, ],
      [[string[], bigint[]] & {owners: string[], percentages: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'ownerProperties'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'properties'): TypedContractMethod<
      [arg0: string, ],
      [[string, bigint, bigint] & {propertyId: string, totalValue: bigint, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'registerProperty'): TypedContractMethod<
      [_propertyId: string, _totalValue: BigNumberish, _initialOwners: AddressLike[], _percentages: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [_propertyId: string, _from: AddressLike, _to: AddressLike, _percentage: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipAdded'): TypedContractEvent<OwnershipAddedEvent.InputTuple, OwnershipAddedEvent.OutputTuple, OwnershipAddedEvent.OutputObject>;
getEvent(key: 'OwnershipRemoved'): TypedContractEvent<OwnershipRemovedEvent.InputTuple, OwnershipRemovedEvent.OutputTuple, OwnershipRemovedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PropertyRegistered'): TypedContractEvent<PropertyRegisteredEvent.InputTuple, PropertyRegisteredEvent.OutputTuple, PropertyRegisteredEvent.OutputObject>;

    filters: {
      
      'OwnershipAdded(string,address,uint256)': TypedContractEvent<OwnershipAddedEvent.InputTuple, OwnershipAddedEvent.OutputTuple, OwnershipAddedEvent.OutputObject>;
      OwnershipAdded: TypedContractEvent<OwnershipAddedEvent.InputTuple, OwnershipAddedEvent.OutputTuple, OwnershipAddedEvent.OutputObject>;
    

      'OwnershipRemoved(string,address)': TypedContractEvent<OwnershipRemovedEvent.InputTuple, OwnershipRemovedEvent.OutputTuple, OwnershipRemovedEvent.OutputObject>;
      OwnershipRemoved: TypedContractEvent<OwnershipRemovedEvent.InputTuple, OwnershipRemovedEvent.OutputTuple, OwnershipRemovedEvent.OutputObject>;
    

      'OwnershipTransferred(string,address,address,uint256)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PropertyRegistered(string,uint256)': TypedContractEvent<PropertyRegisteredEvent.InputTuple, PropertyRegisteredEvent.OutputTuple, PropertyRegisteredEvent.OutputObject>;
      PropertyRegistered: TypedContractEvent<PropertyRegisteredEvent.InputTuple, PropertyRegisteredEvent.OutputTuple, PropertyRegisteredEvent.OutputObject>;
    
    };
  }