/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace PropertyLease {
      
    export type RentPaymentStruct = {amount: BigNumberish, dueDate: BigNumberish, paidDate: BigNumberish, paid: boolean}

    export type RentPaymentStructOutput = [amount: bigint, dueDate: bigint, paidDate: bigint, paid: boolean] & {amount: bigint, dueDate: bigint, paidDate: bigint, paid: boolean }
  
    }

  export interface PropertyLeaseInterface extends Interface {
    getFunction(nameOrSignature: "activateLease" | "createLease" | "getLandlordLeases" | "getLeaseDetails" | "getPendingRent" | "getRentPayments" | "getTenantLeases" | "landlordLeases" | "leases" | "payRent" | "rentPayments" | "returnDeposit" | "tenantLeases" | "terminateLease"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DepositReturned" | "LeaseCreated" | "LeaseTerminated" | "RentPaid"): EventFragment;

    encodeFunctionData(functionFragment: 'activateLease', values: [string]): string;
encodeFunctionData(functionFragment: 'createLease', values: [string, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLandlordLeases', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getLeaseDetails', values: [string]): string;
encodeFunctionData(functionFragment: 'getPendingRent', values: [string]): string;
encodeFunctionData(functionFragment: 'getRentPayments', values: [string]): string;
encodeFunctionData(functionFragment: 'getTenantLeases', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'landlordLeases', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'leases', values: [string]): string;
encodeFunctionData(functionFragment: 'payRent', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'rentPayments', values: [string, BigNumberish]): string;
encodeFunctionData(functionFragment: 'returnDeposit', values: [string]): string;
encodeFunctionData(functionFragment: 'tenantLeases', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'terminateLease', values: [string, string]): string;

    decodeFunctionResult(functionFragment: 'activateLease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLease', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLandlordLeases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLeaseDetails', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRentPayments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTenantLeases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'landlordLeases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'leases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payRent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rentPayments', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'returnDeposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tenantLeases', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'terminateLease', data: BytesLike): Result;
  }

  
    export namespace DepositReturnedEvent {
      export type InputTuple = [leaseId: string, tenant: AddressLike, amount: BigNumberish];
      export type OutputTuple = [leaseId: string, tenant: string, amount: bigint];
      export interface OutputObject {leaseId: string, tenant: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LeaseCreatedEvent {
      export type InputTuple = [propertyId: string, landlord: AddressLike, tenant: AddressLike, monthlyRent: BigNumberish, startDate: BigNumberish, endDate: BigNumberish];
      export type OutputTuple = [propertyId: string, landlord: string, tenant: string, monthlyRent: bigint, startDate: bigint, endDate: bigint];
      export interface OutputObject {propertyId: string, landlord: string, tenant: string, monthlyRent: bigint, startDate: bigint, endDate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LeaseTerminatedEvent {
      export type InputTuple = [leaseId: string, reason: string];
      export type OutputTuple = [leaseId: string, reason: string];
      export interface OutputObject {leaseId: string, reason: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RentPaidEvent {
      export type InputTuple = [leaseId: string, tenant: AddressLike, amount: BigNumberish, paidDate: BigNumberish];
      export type OutputTuple = [leaseId: string, tenant: string, amount: bigint, paidDate: bigint];
      export interface OutputObject {leaseId: string, tenant: string, amount: bigint, paidDate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PropertyLease extends BaseContract {
    
    connect(runner?: ContractRunner | null): PropertyLease;
    waitForDeployment(): Promise<this>;

    interface: PropertyLeaseInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    activateLease: TypedContractMethod<
      [_leaseId: string, ],
      [void],
      'nonpayable'
    >
    

    
    createLease: TypedContractMethod<
      [_propertyId: string, _landlord: AddressLike, _tenant: AddressLike, _monthlyRent: BigNumberish, _securityDeposit: BigNumberish, _startDate: BigNumberish, _rentalPeriodDays: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    getLandlordLeases: TypedContractMethod<
      [_landlord: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getLeaseDetails: TypedContractMethod<
      [_leaseId: string, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint] & {landlord: string, tenant: string, monthlyRent: bigint, securityDeposit: bigint, startDate: bigint, endDate: bigint, status: bigint }],
      'view'
    >
    

    
    getPendingRent: TypedContractMethod<
      [_leaseId: string, ],
      [bigint],
      'view'
    >
    

    
    getRentPayments: TypedContractMethod<
      [_leaseId: string, ],
      [PropertyLease.RentPaymentStructOutput[]],
      'view'
    >
    

    
    getTenantLeases: TypedContractMethod<
      [_tenant: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    landlordLeases: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    leases: TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {propertyId: string, landlord: string, tenant: string, monthlyRent: bigint, securityDeposit: bigint, startDate: bigint, endDate: bigint, rentalPeriodDays: bigint, status: bigint, createdAt: bigint, depositReturned: boolean }],
      'view'
    >
    

    
    payRent: TypedContractMethod<
      [_leaseId: string, _paymentIndex: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    rentPayments: TypedContractMethod<
      [arg0: string, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {amount: bigint, dueDate: bigint, paidDate: bigint, paid: boolean }],
      'view'
    >
    

    
    returnDeposit: TypedContractMethod<
      [_leaseId: string, ],
      [void],
      'nonpayable'
    >
    

    
    tenantLeases: TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    terminateLease: TypedContractMethod<
      [_leaseId: string, _reason: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'activateLease'): TypedContractMethod<
      [_leaseId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createLease'): TypedContractMethod<
      [_propertyId: string, _landlord: AddressLike, _tenant: AddressLike, _monthlyRent: BigNumberish, _securityDeposit: BigNumberish, _startDate: BigNumberish, _rentalPeriodDays: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getLandlordLeases'): TypedContractMethod<
      [_landlord: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getLeaseDetails'): TypedContractMethod<
      [_leaseId: string, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint] & {landlord: string, tenant: string, monthlyRent: bigint, securityDeposit: bigint, startDate: bigint, endDate: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getPendingRent'): TypedContractMethod<
      [_leaseId: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRentPayments'): TypedContractMethod<
      [_leaseId: string, ],
      [PropertyLease.RentPaymentStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTenantLeases'): TypedContractMethod<
      [_tenant: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'landlordLeases'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'leases'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {propertyId: string, landlord: string, tenant: string, monthlyRent: bigint, securityDeposit: bigint, startDate: bigint, endDate: bigint, rentalPeriodDays: bigint, status: bigint, createdAt: bigint, depositReturned: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'payRent'): TypedContractMethod<
      [_leaseId: string, _paymentIndex: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'rentPayments'): TypedContractMethod<
      [arg0: string, arg1: BigNumberish, ],
      [[bigint, bigint, bigint, boolean] & {amount: bigint, dueDate: bigint, paidDate: bigint, paid: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'returnDeposit'): TypedContractMethod<
      [_leaseId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tenantLeases'): TypedContractMethod<
      [arg0: AddressLike, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'terminateLease'): TypedContractMethod<
      [_leaseId: string, _reason: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DepositReturned'): TypedContractEvent<DepositReturnedEvent.InputTuple, DepositReturnedEvent.OutputTuple, DepositReturnedEvent.OutputObject>;
getEvent(key: 'LeaseCreated'): TypedContractEvent<LeaseCreatedEvent.InputTuple, LeaseCreatedEvent.OutputTuple, LeaseCreatedEvent.OutputObject>;
getEvent(key: 'LeaseTerminated'): TypedContractEvent<LeaseTerminatedEvent.InputTuple, LeaseTerminatedEvent.OutputTuple, LeaseTerminatedEvent.OutputObject>;
getEvent(key: 'RentPaid'): TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;

    filters: {
      
      'DepositReturned(string,address,uint256)': TypedContractEvent<DepositReturnedEvent.InputTuple, DepositReturnedEvent.OutputTuple, DepositReturnedEvent.OutputObject>;
      DepositReturned: TypedContractEvent<DepositReturnedEvent.InputTuple, DepositReturnedEvent.OutputTuple, DepositReturnedEvent.OutputObject>;
    

      'LeaseCreated(string,address,address,uint256,uint256,uint256)': TypedContractEvent<LeaseCreatedEvent.InputTuple, LeaseCreatedEvent.OutputTuple, LeaseCreatedEvent.OutputObject>;
      LeaseCreated: TypedContractEvent<LeaseCreatedEvent.InputTuple, LeaseCreatedEvent.OutputTuple, LeaseCreatedEvent.OutputObject>;
    

      'LeaseTerminated(string,string)': TypedContractEvent<LeaseTerminatedEvent.InputTuple, LeaseTerminatedEvent.OutputTuple, LeaseTerminatedEvent.OutputObject>;
      LeaseTerminated: TypedContractEvent<LeaseTerminatedEvent.InputTuple, LeaseTerminatedEvent.OutputTuple, LeaseTerminatedEvent.OutputObject>;
    

      'RentPaid(string,address,uint256,uint256)': TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
      RentPaid: TypedContractEvent<RentPaidEvent.InputTuple, RentPaidEvent.OutputTuple, RentPaidEvent.OutputObject>;
    
    };
  }