/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface PropertyEscrowInterface extends Interface {
    getFunction(nameOrSignature: "approveEscrow" | "approveInspection" | "cancelEscrow" | "createEscrow" | "escrowAgent" | "escrows" | "getBalance" | "getEscrowStatus" | "propertyId" | "releaseToSeller" | "returnDepositToBuyer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DepositReturned" | "EscrowApproved" | "EscrowCancelled" | "EscrowCreated" | "EscrowReleased" | "InspectionApproved"): EventFragment;

    encodeFunctionData(functionFragment: 'approveEscrow', values: [string]): string;
encodeFunctionData(functionFragment: 'approveInspection', values: [string]): string;
encodeFunctionData(functionFragment: 'cancelEscrow', values: [string]): string;
encodeFunctionData(functionFragment: 'createEscrow', values: [string, AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'escrowAgent', values?: undefined): string;
encodeFunctionData(functionFragment: 'escrows', values: [string]): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getEscrowStatus', values: [string]): string;
encodeFunctionData(functionFragment: 'propertyId', values?: undefined): string;
encodeFunctionData(functionFragment: 'releaseToSeller', values: [string]): string;
encodeFunctionData(functionFragment: 'returnDepositToBuyer', values: [string]): string;

    decodeFunctionResult(functionFragment: 'approveEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveInspection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createEscrow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrowAgent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'escrows', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrowStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'propertyId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'releaseToSeller', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'returnDepositToBuyer', data: BytesLike): Result;
  }

  
    export namespace DepositReturnedEvent {
      export type InputTuple = [propertyId: string, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [propertyId: string, recipient: string, amount: bigint];
      export interface OutputObject {propertyId: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowApprovedEvent {
      export type InputTuple = [propertyId: string, approver: AddressLike];
      export type OutputTuple = [propertyId: string, approver: string];
      export interface OutputObject {propertyId: string, approver: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCancelledEvent {
      export type InputTuple = [propertyId: string];
      export type OutputTuple = [propertyId: string];
      export interface OutputObject {propertyId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowCreatedEvent {
      export type InputTuple = [propertyId: string, buyer: AddressLike, seller: AddressLike, escrowAmount: BigNumberish, depositAmount: BigNumberish];
      export type OutputTuple = [propertyId: string, buyer: string, seller: string, escrowAmount: bigint, depositAmount: bigint];
      export interface OutputObject {propertyId: string, buyer: string, seller: string, escrowAmount: bigint, depositAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EscrowReleasedEvent {
      export type InputTuple = [propertyId: string, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [propertyId: string, recipient: string, amount: bigint];
      export interface OutputObject {propertyId: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InspectionApprovedEvent {
      export type InputTuple = [propertyId: string];
      export type OutputTuple = [propertyId: string];
      export interface OutputObject {propertyId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PropertyEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): PropertyEscrow;
    waitForDeployment(): Promise<this>;

    interface: PropertyEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveEscrow: TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >
    

    
    approveInspection: TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >
    

    
    cancelEscrow: TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >
    

    
    createEscrow: TypedContractMethod<
      [_propertyId: string, _buyer: AddressLike, _seller: AddressLike, _depositAmount: BigNumberish, _releaseTime: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    escrowAgent: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    escrows: TypedContractMethod<
      [arg0: string, ],
      [[string, string, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean, boolean] & {buyer: string, seller: string, escrowAmount: bigint, depositAmount: bigint, releaseTime: bigint, createdAt: bigint, buyerApproved: boolean, sellerApproved: boolean, inspectionPassed: boolean, released: boolean, cancelled: boolean }],
      'view'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getEscrowStatus: TypedContractMethod<
      [_propertyId: string, ],
      [[string, string, bigint, bigint, bigint, boolean, boolean, boolean, boolean, boolean] & {buyer: string, seller: string, escrowAmount: bigint, depositAmount: bigint, releaseTime: bigint, buyerApproved: boolean, sellerApproved: boolean, inspectionPassed: boolean, released: boolean, cancelled: boolean }],
      'view'
    >
    

    
    propertyId: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    releaseToSeller: TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >
    

    
    returnDepositToBuyer: TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveEscrow'): TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveInspection'): TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelEscrow'): TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createEscrow'): TypedContractMethod<
      [_propertyId: string, _buyer: AddressLike, _seller: AddressLike, _depositAmount: BigNumberish, _releaseTime: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'escrowAgent'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'escrows'): TypedContractMethod<
      [arg0: string, ],
      [[string, string, bigint, bigint, bigint, bigint, boolean, boolean, boolean, boolean, boolean] & {buyer: string, seller: string, escrowAmount: bigint, depositAmount: bigint, releaseTime: bigint, createdAt: bigint, buyerApproved: boolean, sellerApproved: boolean, inspectionPassed: boolean, released: boolean, cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getEscrowStatus'): TypedContractMethod<
      [_propertyId: string, ],
      [[string, string, bigint, bigint, bigint, boolean, boolean, boolean, boolean, boolean] & {buyer: string, seller: string, escrowAmount: bigint, depositAmount: bigint, releaseTime: bigint, buyerApproved: boolean, sellerApproved: boolean, inspectionPassed: boolean, released: boolean, cancelled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'propertyId'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'releaseToSeller'): TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'returnDepositToBuyer'): TypedContractMethod<
      [_propertyId: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'DepositReturned'): TypedContractEvent<DepositReturnedEvent.InputTuple, DepositReturnedEvent.OutputTuple, DepositReturnedEvent.OutputObject>;
getEvent(key: 'EscrowApproved'): TypedContractEvent<EscrowApprovedEvent.InputTuple, EscrowApprovedEvent.OutputTuple, EscrowApprovedEvent.OutputObject>;
getEvent(key: 'EscrowCancelled'): TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
getEvent(key: 'EscrowCreated'): TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
getEvent(key: 'EscrowReleased'): TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
getEvent(key: 'InspectionApproved'): TypedContractEvent<InspectionApprovedEvent.InputTuple, InspectionApprovedEvent.OutputTuple, InspectionApprovedEvent.OutputObject>;

    filters: {
      
      'DepositReturned(string,address,uint256)': TypedContractEvent<DepositReturnedEvent.InputTuple, DepositReturnedEvent.OutputTuple, DepositReturnedEvent.OutputObject>;
      DepositReturned: TypedContractEvent<DepositReturnedEvent.InputTuple, DepositReturnedEvent.OutputTuple, DepositReturnedEvent.OutputObject>;
    

      'EscrowApproved(string,address)': TypedContractEvent<EscrowApprovedEvent.InputTuple, EscrowApprovedEvent.OutputTuple, EscrowApprovedEvent.OutputObject>;
      EscrowApproved: TypedContractEvent<EscrowApprovedEvent.InputTuple, EscrowApprovedEvent.OutputTuple, EscrowApprovedEvent.OutputObject>;
    

      'EscrowCancelled(string)': TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
      EscrowCancelled: TypedContractEvent<EscrowCancelledEvent.InputTuple, EscrowCancelledEvent.OutputTuple, EscrowCancelledEvent.OutputObject>;
    

      'EscrowCreated(string,address,address,uint256,uint256)': TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
      EscrowCreated: TypedContractEvent<EscrowCreatedEvent.InputTuple, EscrowCreatedEvent.OutputTuple, EscrowCreatedEvent.OutputObject>;
    

      'EscrowReleased(string,address,uint256)': TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
      EscrowReleased: TypedContractEvent<EscrowReleasedEvent.InputTuple, EscrowReleasedEvent.OutputTuple, EscrowReleasedEvent.OutputObject>;
    

      'InspectionApproved(string)': TypedContractEvent<InspectionApprovedEvent.InputTuple, InspectionApprovedEvent.OutputTuple, InspectionApprovedEvent.OutputObject>;
      InspectionApproved: TypedContractEvent<InspectionApprovedEvent.InputTuple, InspectionApprovedEvent.OutputTuple, InspectionApprovedEvent.OutputObject>;
    
    };
  }