/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VerificationRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getVerification" | "recordVerification" | "verificationExists"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "VerificationRecorded"): EventFragment;

    encodeFunctionData(functionFragment: 'getVerification', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'recordVerification', values: [BytesLike, string, string, string]): string;
encodeFunctionData(functionFragment: 'verificationExists', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getVerification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'recordVerification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verificationExists', data: BytesLike): Result;
  }

  
    export namespace VerificationRecordedEvent {
      export type InputTuple = [verificationKey: BytesLike, receiptHash: BytesLike, paymentReference: string, propertyId: string, receiptId: string, recorder: AddressLike, recordedAt: BigNumberish];
      export type OutputTuple = [verificationKey: string, receiptHash: string, paymentReference: string, propertyId: string, receiptId: string, recorder: string, recordedAt: bigint];
      export interface OutputObject {verificationKey: string, receiptHash: string, paymentReference: string, propertyId: string, receiptId: string, recorder: string, recordedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VerificationRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): VerificationRegistry;
    waitForDeployment(): Promise<this>;

    interface: VerificationRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getVerification: TypedContractMethod<
      [verificationKey: BytesLike, ],
      [[string, string, string, string, bigint, string] & {receiptHash: string, paymentReference: string, propertyId: string, receiptId: string, recordedAt: bigint, recorder: string }],
      'view'
    >
    

    
    recordVerification: TypedContractMethod<
      [receiptHash: BytesLike, paymentReference: string, propertyId: string, receiptId: string, ],
      [string],
      'nonpayable'
    >
    

    
    verificationExists: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getVerification'): TypedContractMethod<
      [verificationKey: BytesLike, ],
      [[string, string, string, string, bigint, string] & {receiptHash: string, paymentReference: string, propertyId: string, receiptId: string, recordedAt: bigint, recorder: string }],
      'view'
    >;
getFunction(nameOrSignature: 'recordVerification'): TypedContractMethod<
      [receiptHash: BytesLike, paymentReference: string, propertyId: string, receiptId: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'verificationExists'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'VerificationRecorded'): TypedContractEvent<VerificationRecordedEvent.InputTuple, VerificationRecordedEvent.OutputTuple, VerificationRecordedEvent.OutputObject>;

    filters: {
      
      'VerificationRecorded(bytes32,bytes32,string,string,string,address,uint256)': TypedContractEvent<VerificationRecordedEvent.InputTuple, VerificationRecordedEvent.OutputTuple, VerificationRecordedEvent.OutputObject>;
      VerificationRecorded: TypedContractEvent<VerificationRecordedEvent.InputTuple, VerificationRecordedEvent.OutputTuple, VerificationRecordedEvent.OutputObject>;
    
    };
  }