/** Mobile shell extras merged into non-English locales at load time. */
/** Auto-generated by scripts/generate-locale-chrome.mjs */
export const MOBILE_EXTRAS_BY_CODE = {
  fr: {
    mobile: {
      smartProperty: "Propriété intelligente",
      appShell: {
        offlineCache: "Affichage des listes enregistrées lors de votre dernière visite hors ligne."
      }
    }
  },
  es: {
    mobile: {
      smartProperty: "propiedad inteligente",
      appShell: {
        offlineCache: "Mostrar listados guardados de su última visita sin conexión."
      }
    }
  },
  pt: {
    mobile: {
      smartProperty: "Propriedade inteligente",
      appShell: {
        offlineCache: "Mostrando listagens salvas da sua última visita off-line."
      }
    }
  },
  de: {
    mobile: {
      smartProperty: "Intelligente Immobilie",
      appShell: {
        offlineCache: "Zeigt gespeicherte Einträge von Ihrem letzten Besuch an, während Sie offline sind."
      }
    }
  },
  it: {
    mobile: {
      smartProperty: "Proprietà intelligente",
      appShell: {
        offlineCache: "Visualizzazione delle inserzioni salvate dalla tua ultima visita mentre sei offline."
      }
    }
  },
  nl: {
    mobile: {
      smartProperty: "Slimme eigendom",
      appShell: {
        offlineCache: "Toont opgeslagen vermeldingen van uw laatste bezoek terwijl u offline was."
      }
    }
  },
  ru: {
    mobile: {
      smartProperty: "Умная собственность",
      appShell: {
        offlineCache: "Показ сохраненных объявлений с вашего последнего посещения в автономном режиме."
      }
    }
  },
  tr: {
    mobile: {
      smartProperty: "Akıllı özellik",
      appShell: {
        offlineCache: "Çevrimdışıyken son ziyaretinize ait kayıtlı listeler gösteriliyor."
      }
    }
  },
  pl: {
    mobile: {
      smartProperty: "Inteligentna nieruchomość",
      appShell: {
        offlineCache: "Wyświetlanie zapisanych ofert z Twojej ostatniej wizyty w trybie offline."
      }
    }
  },
  sv: {
    mobile: {
      smartProperty: "Smart egendom",
      appShell: {
        offlineCache: "Visar sparade uppgifter från ditt senaste besök när du är offline."
      }
    }
  },
  uk: {
    mobile: {
      smartProperty: "Розумна власність",
      appShell: {
        offlineCache: "Показ збережених списків із вашого останнього відвідування в режимі офлайн."
      }
    }
  },
  ar: {
    mobile: {
      smartProperty: "خاصية ذكية",
      appShell: {
        offlineCache: "عرض القوائم المحفوظة من زيارتك الأخيرة أثناء عدم الاتصال بالإنترنت."
      }
    }
  },
  tw: {
    mobile: {
      smartProperty: "Smart agyapade",
      appShell: {
        offlineCache: "Kyerɛw nneɛma a wɔakora so a efi wo nsrahwɛ a etwa to bere a wunni intanɛt so no."
      }
    }
  },
  ha: {
    mobile: {
      smartProperty: "Smart dukiya",
      appShell: {
        offlineCache: "Nuna ajiyayyun jeri na ziyararka ta ƙarshe yayin da ba layi ba."
      }
    }
  },
  sw: {
    mobile: {
      smartProperty: "Mali ya Smart",
      appShell: {
        offlineCache: "Inaonyesha uorodheshaji uliohifadhiwa kutoka kwa ziara yako ya mwisho ukiwa nje ya mtandao."
      }
    }
  },
  yo: {
    mobile: {
      smartProperty: "Smart ohun ini",
      appShell: {
        offlineCache: "Ṣe afihan awọn atokọ ti o fipamọ lati ibẹwo rẹ kẹhin lakoko offline."
      }
    }
  },
  ig: {
    mobile: {
      smartProperty: "Ngwongwo mara mma",
      appShell: {
        offlineCache: "Na-egosi ndepụta echekwara na nleta ikpeazụ gị mgbe ị na-anọghị n'ịntanetị."
      }
    }
  },
  am: {
    mobile: {
      smartProperty: "ብልህ ንብረት",
      appShell: {
        offlineCache: "ከመስመር ውጭ ሆነው የመጨረሻ ጉብኝትዎ የተቀመጡ ዝርዝሮችን በማሳየት ላይ።"
      }
    }
  },
  ee: {
    mobile: {
      smartProperty: "Nunya ƒe nunɔamesi",
      appShell: {
        offlineCache: "Nusiwo nèdzra ɖo tso wò sasrãkpɔ mamlɛtɔ me ɖeɖefia esime mèle Internet dzi o."
      }
    }
  },
  zu: {
    mobile: {
      smartProperty: "Impahla ehlakaniphile",
      appShell: {
        offlineCache: "Ibonisa izinhlu ezilondoloziwe kusukela ekuvakasheni kwakho kokugcina ngesikhathi ungaxhunyiwe ku-inthanethi."
      }
    }
  },
  af: {
    mobile: {
      smartProperty: "Slim eiendom",
      appShell: {
        offlineCache: "Wys tans gestoorde lysinskrywings van jou laaste besoek terwyl jy vanlyn is."
      }
    }
  },
  zh: {
    mobile: {
      smartProperty: "智慧物业",
      appShell: {
        offlineCache: "显示您上次离线访问时保存的列表。"
      }
    }
  },
  hi: {
    mobile: {
      smartProperty: "स्मार्ट संपत्ति",
      appShell: {
        offlineCache: "ऑफ़लाइन रहते हुए आपकी पिछली यात्रा की सहेजी गई सूचियाँ दिखा रहा है।"
      }
    }
  },
  ja: {
    mobile: {
      smartProperty: "スマートプロパティ",
      appShell: {
        offlineCache: "オフライン時の前回の訪問時に保存されたリストを表示します。"
      }
    }
  },
  ko: {
    mobile: {
      smartProperty: "스마트 자산",
      appShell: {
        offlineCache: "오프라인 상태에서 마지막 방문 시 저장된 목록을 표시합니다."
      }
    }
  },
  vi: {
    mobile: {
      smartProperty: "Tài sản thông minh",
      appShell: {
        offlineCache: "Hiển thị danh sách đã lưu từ lần truy cập cuối cùng của bạn khi ngoại tuyến."
      }
    }
  },
  id: {
    mobile: {
      smartProperty: "Properti cerdas",
      appShell: {
        offlineCache: "Menampilkan daftar tersimpan dari kunjungan terakhir Anda saat offline."
      }
    }
  },
  ms: {
    mobile: {
      smartProperty: "Harta pintar",
      appShell: {
        offlineCache: "Menunjukkan penyenaraian yang disimpan daripada lawatan terakhir anda semasa di luar talian."
      }
    }
  },
  th: {
    mobile: {
      smartProperty: "ทรัพย์สินอัจฉริยะ",
      appShell: {
        offlineCache: "แสดงรายการที่บันทึกไว้จากการเข้าชมครั้งล่าสุดของคุณขณะออฟไลน์"
      }
    }
  },
  bn: {
    mobile: {
      smartProperty: "স্মার্ট সম্পত্তি",
      appShell: {
        offlineCache: "অফলাইনে থাকাকালীন আপনার শেষ পরিদর্শন থেকে সংরক্ষিত তালিকা দেখানো হচ্ছে।"
      }
    }
  },
  ur: {
    mobile: {
      smartProperty: "سمارٹ پراپرٹی",
      appShell: {
        offlineCache: "آف لائن رہتے ہوئے آپ کے آخری وزٹ سے محفوظ کردہ فہرستیں دکھا رہا ہے۔"
      }
    }
  },
  fa: {
    mobile: {
      smartProperty: "دارایی هوشمند",
      appShell: {
        offlineCache: "نمایش لیست های ذخیره شده از آخرین بازدید شما در حالت آفلاین."
      }
    }
  }
};

export function getMobileExtras(code) {
  return MOBILE_EXTRAS_BY_CODE[code] ?? {};
}
